### PR TITLE
3. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar

### LINKED ISSUE #3: 3. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouter.com/en/6.14.2/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by StefieCaff**
## Description
Imported NavLink from react-router-dom. Implemented NavLink navigation in Layout.jsx-- we can manage styling and active class later.
We decided to use NavLinks instead of traditional <a> tags to get the full benefit of using react-router-dom. The NavLink component adds active functionality and accessibility in addition to styling potential for our app.

## Related Issue
closes #3 

## Acceptance Criteria

 - [x] The nav element is added to the Layout component
 - [x] Links to the "Home", "List", and "Add item" pages of the app are In the nav element
 - [x] The links all function as expected using the NavLink component from react-router-dom
 
## Type of Changes

Enhancement

### Before

https://github.com/the-collab-lab/tcl-66-smart-shopping-list/assets/108297341/9d3c1f34-d24d-4c85-bc6d-5d05584238b6

### After

https://github.com/the-collab-lab/tcl-66-smart-shopping-list/assets/108297341/0f7cf680-f53f-42cf-b045-28c3788293f0

## Testing Steps / QA Criteria

1. Run npm start in terminal
2. Click home/list/manage-list in navigation to see page change and active link

### CODE REVIEW

**Comment by eonflower** [comment]
Looks good to me! The only thing that I notice (that Emilio brought up to me), is that the instructions say to have links for "home", "list", and "add item", but it looks like the project set us up with "manage list" instead. Might just be a wonky discrepancy passed down to us.

**Review by eonflower — APPROVED** [review]
Looks good to me! The only thing that I notice (that Emilio brought up to me), is that the instructions say to have links for "home", "list", and "add item", but it looks like the project set us up with "manage list" instead. Might just be a wonky discrepancy passed down to us.

**Comment by 3campos** [comment]
I reviewed your code and ran it locally. Using NavLink components was a great choice! When I ran the code locally, the links worked as expected. Nice job!

I echo Aloe's comment regarding the instruction for an "Add Item" link in the nav element. If our mentors said to leave the "Manage List" link in the nav element instead of "Add Item", then you're all set to have our mentors begin their review of your work!

**Review by 3campos — APPROVED** [review]
Please see my previous comment regarding the instructions for this issue.

**Review by jeremiahfallin — APPROVED** [review]
Nice work, looks good to me! Feel free to merge when you're ready.

**Pull request merged**
